jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
      resource_class: large
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
      - run: wget https://github.com/maximumadmin/zramd/releases/download/v0.9.2/zramd_amd64.deb
      - run: apt install ./zramd_amd64.deb -y
      - run: zramd start
      - run: echo "$PWD"
      - run: ./download.sh
      - run: ./ac.sh
