jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
      resource_class: large
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
      - run: git clone https://gitlab.com/OrangeFox/sync.git # (or, using ssh, "git clone git@gitlab.com:OrangeFox/sync.git")
      - run: cd sync/
      - run: ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
      - run: cd ~/fox_12.1
      - run: git clone https://gitlab.com/NopeNopeGuy/whyred-4-19-fbe device/xiaomi/whyred
      - run: export LC_ALL="C"
      - run: export FOX_BUILD_DEVICE=whyred
      - run: export OF_FORCE_PREBUILT_KERNEL=1
      - run: source build/envsetup.sh
      - run: lunch twrp_whyred-eng && mka adbd recoveryimage
      - run: curl --upload-file out/target/product/whyred/Orange*.img https://transfer.sh/Orangefox
