jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
      resource_class: large
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
      - run: echo "$PWD"
      - run: ./download.sh
      - run: ./ac.sh
